### ISSUE TITLE
How to find gdash

### ISSUE THREAD

**Issue by mabushey** [kadalu/gdash#4]
I did a git clone. It's at commit a3d11d280d. Where is the gdash executable, or how do I compile it?

Do I have to install pip (I'm guessing this is python-pip)? I hate crap package managers like gem/composer that want to do a substandard duplication/implementation of apt. Since it's written in python, can't I just run a python script or cat the .py files together and run?

I need to install this via Ansible, so running all kinds of goofy environmental commands is not realistic.

**Comment by aravindavk** [comment]
If you don't want to use pip. cd into cloned directory and run,

python setup.py install

I don't think language specific package managers are crap. pip is one such package manager for Python. You may not get all the libraries from Ubuntu repositories all the time. Also the version available in apt-get may be older and your app needs newer version. Also these package managers are helpful when you create a python app using virtualenv.

I will plan to create deb/rpm package for this project. So that this will be really easy to install using apt-get or whatever.

**Comment by mabushey** [comment]
A deb for gdash would be awesome!

I had to install `python-setuptools` and `python-flask`. 

\# gdash --host f01
 \* Running on http://0.0.0.0:8080/

\# telnet 127.0.0.1 8080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET / HTTP/1.1             
host: gdash.example.com

HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: text/html
Content-Length: 291
Server: Werkzeug/0.9.6 Python/2.7.10
Date: Wed, 03 Jun 2015 20:39:00 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
\<title>500 Internal Server Error\</title>
\<h1>Internal Server Error\</h1>
\<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.\</p>
Connection closed by foreign host.

Using an Nginx config of:
server {
  listen 80;
  server_name gdash.example.com;
  location / {
    proxy_pass http://127.0.0.1:8080/;
  }
}

Also gives a 500 error.

**Comment by aravindavk** [comment]
Fixed now with the latest release. Gdash is rewritten using CherryPy and ReactJS
